= BlueXP 의 작업 공간과 FSx for ONTAP 파일 시스템 연결
:allow-uri-read: 




=== BlueXP 의 작업 공간과 FSx for ONTAP 파일 시스템 연결

2024년 11월 BlueXP 통합 이후 새로 생성된 FSx for ONTAP 파일 시스템은 BlueXP 의 어떤 작업 공간과도 연결되지 않았습니다.  이제 FSx for ONTAP 파일 시스템을 생성하거나 검색하면 해당 파일 시스템이 BlueXP 계정 내의 하나의 작업 공간과 연결됩니다.

작업 공간과 연결되지 않은 기존 FSx for ONTAP 파일 시스템이 있는 경우 BlueXP 에서 해당 파일 시스템을 작업 공간과 연결하는 데 도움을 드립니다.  당신은 할 수 있습니다link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-get-help.html#create-a-case-with-netapp-support["NetApp 지원에 케이스 생성"^] BlueXP 콘솔 내에서.  서비스로 *Workload Factory*를 선택하세요.



=== BlueXP 캔버스에서 파일 시스템 제거

이제 BlueXP 캔버스의 작업 공간에서 FSx for ONTAP 파일 시스템을 제거할 수 있습니다.  이 작업을 수행하면 파일 시스템을 하나의 작업 공간에서 분리하여 동일한 BlueXP 계정 내의 다른 작업 공간과 연결할 수 있습니다.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-remove-filesystem.html["BlueXP 에서 작업 공간에서 FSx for ONTAP 파일 시스템을 제거하는 방법을 알아보세요."^]



=== 작업 모니터링 및 추적을 위한 추적기 사용 가능

새로운 모니터링 기능인 Tracker는 BlueXP Amazon FSx for NetApp ONTAP 에서 사용할 수 있습니다.  Tracker를 사용하면 자격 증명, 저장소 및 링크 작업의 진행 상황과 상태를 모니터링하고 추적하고, 작업 작업 및 하위 작업에 대한 세부 정보를 검토하고, 문제나 오류를 진단하고, 실패한 작업에 대한 매개변수를 편집하고, 실패한 작업을 다시 시도할 수 있습니다.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-monitor-operations.html["BlueXP 에서 FSx for ONTAP 작업을 모니터링하고 추적하는 방법을 알아보세요."^]



=== BlueXP 워크로드에서 사용 가능한 CloudShell

CloudShell은 BlueXP 콘솔 내에서 BlueXP 워크로드를 사용할 때 사용할 수 있습니다.  CloudShell을 사용하면 BlueXP 계정에서 제공한 AWS 및 ONTAP 자격 증명을 사용하여 셸과 유사한 환경에서 AWS CLI 명령이나 ONTAP CLI 명령을 실행할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["CloudShell을 사용하세요"^]
