---
sidebar: sidebar 
permalink: use/task-monitor-operations.html 
keywords: monitor jobs, track jobs, monitor, track, NetApp Console, bluexp 
summary: NetApp 콘솔의 Tracker를 사용하여 FSx for ONTAP 작업을 추적하고 작업 진행 상황을 모니터링합니다. 
---
= NetApp 콘솔의 Tracker를 사용하여 FSx for ONTAP 작업을 모니터링합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp 콘솔의 Tracker를 사용하여 FSx for ONTAP 작업의 실행을 모니터링하고 추적하며 작업 진행 상황을 모니터링합니다.

.이 작업에 관하여
NetApp 콘솔은 작업 모니터링 기능인 Tracker를 제공하여 자격 증명, FSx for ONTAP 및 링크 작업의 진행 상황과 상태를 모니터링하고 추적하고, 작업 작업과 하위 작업에 대한 세부 정보를 검토하고, 문제나 오류를 진단할 수 있습니다.

Tracker에서는 다양한 작업을 수행할 수 있습니다.  작업을 기간(지난 24시간, 7일, 14일 또는 30일), 작업량, 상태 및 사용자별로 필터링할 수 있습니다. 검색 기능을 사용하여 작업을 찾고 작업 표를 CSV 파일로 다운로드할 수 있습니다.  언제든지 Tracker를 새로 고칠 수 있습니다.  실패한 작업을 빠르게 다시 시도하거나 실패한 작업에 대한 매개변수를 편집하여 작업을 다시 시도할 수 있습니다.

Tracker는 작업에 따라 두 가지 수준의 모니터링을 지원합니다.  파일 시스템 배포와 같은 각 작업에는 작업 설명, 상태, 시작 시간, 작업 기간, 사용자, 지역, 프록시 리소스, 작업 ID 및 모든 관련 하위 작업이 표시됩니다.  API 응답을 보면 작업 중에 무슨 일이 일어났는지 이해할 수 있습니다.

예를 들어 추적 작업 수준::
+
--
* 레벨 1(상위 작업): 파일 시스템 배포를 추적합니다.
* 레벨 2(하위 작업): 파일 시스템 배포와 관련된 하위 작업을 추적합니다.


--
작업 상태:: Tracker에서의 작업 상태는 _진행 중_, _성공_, _실패_로 구분됩니다.
동작 주파수:: 작업 빈도는 작업 유형과 일정에 따라 결정됩니다.
이벤트 보존:: 이벤트는 사용자 인터페이스에 30일 동안 보관됩니다.




== 작업 추적 및 모니터링

Tracker를 사용하여 NetApp 콘솔에서 작업을 추적하고 모니터링하세요.

.단계
. NetApp 콘솔 메뉴에서 *워크로드*를 선택한 다음 *관리*를 선택합니다.
. 관리 메뉴에서 *추적기*를 선택하세요.
. Tracker에서 작업을 보거나 필터 또는 검색을 사용하여 결과를 좁힐 수 있습니다.  *CSV 내보내기*를 선택하면 모든 작업에 대한 보고서를 다운로드할 수도 있습니다.




== API 요청 보기

Tracker의 작업에 대한 API 요청을 Codebox에서 확인하세요.

.단계
. Tracker에서 작업을 선택하세요.
. 세 개의 점 메뉴를 선택한 다음 *API 요청 보기*를 선택하세요.




== 실패한 작업을 다시 시도하세요

Tracker에서 실패한 작업을 다시 시도합니다.  실패한 작업을 다시 시도하면 Tracker에서 모니터링할 수 있는 새 작업이 시작됩니다.

실패한 작업의 오류 메시지를 복사할 수도 있습니다.


NOTE: 실패한 작업은 한 번만 다시 시도할 수 있습니다.

.단계
. 추적기에서 실패한 작업을 선택합니다.
. 세 개의 점 메뉴를 선택한 다음 *다시 시도*를 선택하세요.


.결과
작업이 다시 시작되고 Tracker에 새 작업으로 나타납니다.



== 실패한 작업을 편집하고 다시 시도합니다.

실패한 작업의 매개변수를 편집하고 Tracker 외부에서 작업을 다시 시도하세요.

.단계
. 추적기에서 실패한 작업을 선택합니다.
. 세 개의 점 메뉴를 선택한 다음 *편집 및 다시 시도*를 선택하세요.
+
예를 들어 볼륨 생성 등의 작업 페이지로 리디렉션되어 매개변수를 편집하고 작업을 다시 시도할 수 있습니다.



.결과
작업이 재개되었습니다.  추적기로 가서 작업 상태를 확인하세요.
