---
sidebar: sidebar 
permalink: use/task-manage-fsx-systems.html 
keywords: amazon fsx for netapp ontap, fsx, manage fsx for ontap system, delete fsx for ontap system, remove fsx for ontap system, throughput capacity, change throughput, automatic capacity management, capacity management, storage capacity, replication, classification, sync, backup, recovery, bluexp, NetApp Console 
summary: NetApp Console 에서 FSx for ONTAP 시스템을 생성하거나 검색한 후에는 파일 시스템을 관리하고 백업 및 복구와 같은 기능을 제공하는 NetApp 데이터 서비스를 사용할 수 있습니다. 
---
= NetApp Console 에서 FSx for ONTAP 파일 시스템 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Console 에서 FSx for ONTAP 시스템을 생성하거나 검색한 후 볼륨 생성, 스토리지 VM 관리, 데이터 보호, 파일 시스템 관리를 통해 파일 시스템을 관리할 수 있습니다.  콘솔을 사용하면 백업 및 복구, 데이터 분류, 데이터 동기화 등의 기능을 제공하는 데이터 서비스를 사용할 수도 있습니다.



== NetApp Workloads를 사용하여 파일 시스템 관리

NetApp Console Systems 페이지에서 FSx for ONTAP 시스템을 열면 NetApp Workloads로 이동합니다. Workloads는 업계 모범 사례를 활용하여 Amazon FSx for NetApp ONTAP를 사용하는 주요 워크로드를 계획, 프로비저닝 및 운영하는 지능형 최적화 및 자동화 서비스입니다.

https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["NetApp Workloads를 사용하여 파일 시스템을 관리하는 방법을 알아보세요."^]



== ONTAP 시스템 관리자를 사용하여 파일 시스템 관리

ONTAP 시스템 관리자 인터페이스를 사용하면 콘솔에서 직접 FSx for ONTAP 파일 시스템을 관리할 수 있습니다. System Manager를 사용하려면 콘솔 에이전트 또는 AWS Lambda 링크가 필요합니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["링크 사용에 대해 알아보세요"^]



== Amazon CloudFormation을 사용하여 파일 시스템 관리

Amazon CloudFormation을 사용하여 FSx for ONTAP 파일 시스템 리소스(볼륨, CIFS 공유, 내보내기 정책 등)를 프로비저닝하고 관리할 수 있습니다.

link:https://github.com/NetApp/NetApp-CloudFormation-FSx-ONTAP-provider["NetApp CloudFormation FSx for ONTAP 공급자 GitHub 저장소"^]



== 파일 시스템과 함께 NetApp 데이터 서비스 사용

FSx for ONTAP 파일 시스템과 함께 NetApp 데이터 서비스를 사용하면 데이터를 백업하고 복구하고, 데이터를 전송하고 동기화하고, 데이터를 스캔하고 분류하고, 데이터를 복제하고, 액세스 속도를 높이거나 트래픽을 오프로드할 수 있습니다.



=== 데이터 백업 및 복구

NetApp Backup and Recovery 온프레미스와 클라우드 모두에서 NetApp ONTAP 데이터, 데이터베이스 및 가상 머신에 대한 효율적이고 안전하며 비용 효율적인 데이터 보호 기능을 제공합니다.

link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["NetApp Backup and Recovery 시작하기"^]



=== 데이터 전송 및 동기화

NetApp Copy and Sync 온프레미스와 클라우드 개체 저장소 간에 NAS 데이터를 전송하기 위한 클라우드 복제 및 동기화 서비스입니다.

link:https://docs.netapp.com/us-en/data-services-copy-sync/task-quick-start.html["NetApp Copy and Sync 시작하기"^]



=== 데이터 스캔 및 분류

NetApp Data Classification 사용하면 조직의 하이브리드 멀티클라우드에서 데이터를 스캔하고 분류할 수 있습니다.

link:https://docs.netapp.com/us-en/data-services-data-classification/index.html["NetApp Data Classification 시작하기"^]



=== 접근 속도를 높이거나 트래픽을 오프로드합니다.

NetApp Volume Caching 원격 장소에 지속적이고 쓰기 가능한 볼륨을 제공합니다.  볼륨 캐싱을 사용하면 데이터 액세스 속도를 높이거나 액세스가 많은 볼륨의 트래픽을 오프로드할 수 있습니다.

link:https://docs.netapp.com/us-en/console-volume-caching/get-started/cache-intro.html["NetApp Volume Caching 시작하기"^]
