---
sidebar: sidebar 
permalink: use/task-manage-fsx-systems.html 
keywords: amazon fsx for netapp ontap, fsx, manage fsx for ontap system, delete fsx for ontap system, remove fsx for ontap system, throughput capacity, change throughput, automatic capacity management, capacity management, storage capacity, replication, classification, sync, backup, recovery, bluexp, NetApp Console 
summary: NetApp Console 에서 FSx for ONTAP 시스템을 생성하거나 검색한 후에는 파일 시스템을 관리하고 백업 및 복구와 같은 기능을 제공하는 NetApp 데이터 서비스를 사용할 수 있습니다. 
---
= NetApp Console 에서 FSx for ONTAP 파일 시스템 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Console 에서 FSx for ONTAP 시스템을 생성하거나 검색한 후 볼륨 생성, 스토리지 VM 관리, 데이터 보호, 파일 시스템 관리를 통해 파일 시스템을 관리할 수 있습니다.  콘솔을 사용하면 백업 및 복구, 데이터 분류, 데이터 동기화 등의 기능을 제공하는 데이터 서비스를 사용할 수도 있습니다.



== NetApp Workloads를 사용하여 파일 시스템 관리

NetApp Console 시스템 페이지에서 FSx for ONTAP 시스템을 열면 NetApp 워크로드로 이동하게 됩니다.  Workloads는 Amazon FSx for NetApp ONTAP 사용하여 주요 워크로드를 설계, 설정 및 운영하기 위해 업계 모범 사례를 활용하는 지능형 최적화 및 자동화 서비스입니다.

https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["NetApp Workloads를 사용하여 파일 시스템을 관리하는 방법을 알아보세요."^]



== ONTAP 시스템 관리자를 사용하여 파일 시스템 관리

ONTAP 시스템 관리자 인터페이스를 사용하면 콘솔에서 직접 FSx for ONTAP 파일 시스템을 관리할 수 있습니다. System Manager를 사용하려면 콘솔 에이전트 또는 AWS Lambda 링크가 필요합니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["링크 사용에 대해 알아보세요"^]



== Amazon CloudFormation을 사용하여 파일 시스템 관리

Amazon CloudFormation을 사용하여 FSx for ONTAP 파일 시스템 리소스(볼륨, CIFS 공유, 내보내기 정책 등)를 프로비저닝하고 관리할 수 있습니다.

link:https://github.com/NetApp/NetApp-CloudFormation-FSx-ONTAP-provider["NetApp CloudFormation FSx for ONTAP 공급자 GitHub 저장소"^]



== 파일 시스템과 함께 NetApp 데이터 서비스 사용

FSx for ONTAP 파일 시스템과 함께 NetApp 데이터 서비스를 사용하면 데이터를 백업하고 복구하고, 데이터를 전송하고 동기화하고, 데이터를 스캔하고 분류하고, 데이터를 복제하고, 액세스 속도를 높이거나 트래픽을 오프로드할 수 있습니다.



=== 데이터 백업 및 복구

NetApp Backup and Recovery 온프레미스와 클라우드 모두에서 NetApp ONTAP 데이터, 데이터베이스 및 가상 머신에 대한 효율적이고 안전하며 비용 효율적인 데이터 보호 기능을 제공합니다.

link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["NetApp Backup and Recovery 시작하기"^]



=== 데이터 전송 및 동기화

NetApp Copy and Sync 온프레미스와 클라우드 개체 저장소 간에 NAS 데이터를 전송하기 위한 클라우드 복제 및 동기화 서비스입니다.

link:https://docs.netapp.com/us-en/data-services-copy-sync/task-quick-start.html["NetApp Copy and Sync 시작하기"^]



=== 데이터 스캔 및 분류

NetApp Data Classification 사용하면 조직의 하이브리드 멀티클라우드에서 데이터를 스캔하고 분류할 수 있습니다.

link:https://docs.netapp.com/us-en/data-services-data-classification/index.html["NetApp Data Classification 시작하기"^]



=== 데이터 복제

백업 및 재해 복구를 지원하기 위해 데이터를 복제합니다. FSx for ONTAP 파일 시스템과 Cloud Volumes ONTAP 간의 데이터 복제는 NetApp Replication 사용하여 수행할 수 있습니다. 복제를 사용하면 ONTAP 스토리지 시스템 간에 데이터를 복제하여 클라우드 또는 클라우드 간의 백업 및 재해 복구를 지원할 수 있습니다.

link:https://docs.netapp.com/us-en/data-services-replication/task-replicating-data.html["NetApp Replication 시작하기"^]

두 개의 FSx for ONTAP 파일 시스템 간, 그리고 온프레미스 ONTAP 시스템과 FSx for ONTAP 파일 시스템 간의 데이터 복제는 NetApp Console 시스템 페이지에서 가능합니다.

.시작하기 전에
시작하기 전에 다음 사항을 고려하세요.

* 두 FSx for ONTAP 파일 시스템 간 또는 온프레미스 ONTAP 시스템과 FSx for ONTAP 파일 시스템 간에 데이터를 복제하려면 파일 시스템에 연결할 수 있는 콘솔 에이전트를 선택하거나 파일 시스템을 입력하여 링크를 연결해야 합니다.
* 사용 가능, 생성됨 또는 잘못 구성됨 상태가 아닌 볼륨의 경우 복제가 지원되지 않으며, 이 경우 ONTAP 버전이 호환되지 않습니다.


.단계
. NetApp Console 시스템 페이지에서 소스 FSx for ONTAP 파일 시스템이나 온프레미스 ONTAP 시스템을 대상 FSx for ONTAP 파일 시스템 위로 끌어다 놓고 *복제*를 선택합니다.
. 복제 생성 페이지에서 복제할 소스 볼륨을 선택한 후 *다음*을 클릭합니다.
. 복제 대상에서 다음을 제공합니다.
+
.. *대상 이름*: 대상 이름은 캔버스에서 드래그 앤 드롭 작업 중에 이전에 선택되었습니다.
.. *저장소 VM 이름*: 드롭다운 메뉴에서 저장 VM을 선택합니다.  선택한 스토리지 VM은 이 복제 관계에서 선택한 모든 볼륨의 대상입니다.
.. *볼륨 이름*: 대상 볼륨 이름은 다음 형식으로 자동 생성됩니다. `{OriginalVolumeName}_copy` .  자동 생성된 볼륨 이름을 사용하거나 다른 볼륨 이름을 입력할 수 있습니다.
.. *사용 사례*: 복제에 대한 다음 사용 사례 중 하나를 선택하세요.  선택한 사용 사례에 따라 Workload Factory는 모범 사례에 따라 권장 값으로 양식을 채웁니다.  권장되는 값을 수락하거나 양식을 작성하면서 변경할 수 있습니다.
+
*** 마이그레이션: 데이터를 대상 FSx for ONTAP 파일 시스템으로 전송합니다.
*** 핫 재해 복구: 중요 작업 부하에 대한 높은 가용성과 신속한 재해 복구를 보장합니다.
*** 콜드 또는 아카이브 재해 복구:
+
**** 콜드 재해 복구: 더 긴 복구 시간 목표(RTO) 및 복구 지점 객체(RPO)를 사용하여 비용을 절감합니다.
**** 보관: 장기 보관 및 규정 준수를 위해 데이터 복제


*** 다른
+
또한, 사용 사례 선택에 따라 복제 정책 또는 SnapMirror 정책(ONTAP)이 결정됩니다.  복제 정책을 설명하는 데 사용되는 용어는 다음에서 유래되었습니다.link:https://docs.netapp.com/us-en/ontap/data-protection/default-protection-policies-concept.html["ONTAP 9 문서"^] .

+
**** 마이그레이션 및 기타의 경우 복제 정책은 _MirrorAllSnapshots_라고 합니다.  _MirrorAllSnapshots_는 모든 스냅샷과 최신 활성 파일 시스템을 미러링하기 위한 비동기 정책입니다.
**** 핫, 콜드 또는 아카이브 재해 복구의 경우 복제 정책을 _MirrorAndVault_라고 합니다.  _MirrorAndVault_는 최신 활성 파일 시스템과 일일 및 주간 스냅샷을 미러링하기 위한 비동기 및 볼트 정책입니다.
+
모든 사용 사례에서 장기 보존을 위해 스냅샷을 활성화하는 경우 기본 복제 정책은 _MirrorAndVault_입니다.





.. *계층화 정책*: 대상 볼륨에 저장된 데이터에 대한 계층화 정책을 선택합니다.  계층화 정책은 선택한 사용 사례에 권장되는 계층화 정책으로 기본 설정됩니다.
+
Workload Factory 콘솔을 사용하여 볼륨을 생성할 때 기본 계층화 정책은 _균형(자동)_입니다.  볼륨 계층화 정책에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["볼륨 저장 용량"^] AWS FSx for NetApp ONTAP 문서.  Workload Factory는 계층화 정책에 대해 Workload Factory 콘솔에서 사용 사례 기반 이름을 사용하고 FSx for ONTAP 계층화 정책 이름을 괄호 안에 포함합니다.

+
마이그레이션 사용 사례를 선택한 경우 Workload Factory는 소스 볼륨의 계층화 정책을 대상 볼륨으로 자동으로 복사합니다.  계층화 정책을 복사하려면 선택을 취소하고 복제를 위해 선택한 볼륨에 적용되는 계층화 정책을 선택합니다.

.. *최대 전송 속도*: *제한됨*을 선택하고 최대 전송 한도를 MB/s로 입력합니다.  또는 *무제한*을 선택하세요.
+
제한이 없으면 네트워크 및 애플리케이션 성능이 저하될 수 있습니다.  또는 재해 복구에 주로 사용되는 작업 부하와 같이 중요한 작업 부하의 경우 FSx for ONTAP 파일 시스템에 무제한 전송 속도를 사용하는 것이 좋습니다.



. 복제 설정에서 다음을 제공합니다.
+
.. *복제 간격*: 스냅샷이 소스 볼륨에서 대상 볼륨으로 전송되는 빈도를 선택합니다.
.. *장기 보존*: 선택적으로 장기 보존을 위해 스냅샷을 활성화합니다.  장기 보존을 통해 사이트 전체에 장애가 발생하더라도 비즈니스 서비스는 계속 운영될 수 있으며, 보조 사본을 사용하여 애플리케이션이 투명하게 장애 조치되도록 지원합니다.
+
장기 보존이 없는 복제는 _MirrorAllSnapshots_ 정책을 사용합니다.  장기 보존을 활성화하면 _MirrorAndVault_ 정책이 복제에 할당됩니다.

+
장기 보존을 활성화하는 경우 기존 정책을 선택하거나 새 정책을 만들어 복제할 스냅샷과 보존할 스냅샷 수를 정의합니다.

+

NOTE: 장기 보존을 위해서는 소스와 타겟 라벨이 일치해야 합니다.  원하시면 Workload Factory에서 누락된 레이블을 생성해 드릴 수 있습니다.

+
*** *기존 정책 선택*: 드롭다운 메뉴에서 기존 정책을 선택하세요.
*** *새 정책 만들기*: *정책 이름*을 입력하세요.


.. *변경 불가능한 스냅샷*: 선택 사항.  보존 기간 동안 이 정책에서 생성된 스냅샷이 삭제되는 것을 방지하려면 *변경 불가능한 스냅샷 사용*을 선택합니다.
+
*** *보존 기간*을 시간, 일, 월 또는 년 단위로 설정합니다.
*** *스냅샷 정책*: 표에서 스냅샷 정책 빈도와 보관할 복사본 수를 선택합니다.  두 개 이상의 스냅샷 정책을 선택할 수 있습니다.






. *만들기*를 선택하세요.




=== 접근 속도를 높이거나 트래픽을 오프로드합니다.

NetApp Volume Caching 원격 장소에 지속적이고 쓰기 가능한 볼륨을 제공합니다.  볼륨 캐싱을 사용하면 데이터 액세스 속도를 높이거나 액세스가 많은 볼륨의 트래픽을 오프로드할 수 있습니다.

link:https://docs.netapp.com/us-en/console-volume-caching/get-started/cache-intro.html["NetApp Volume Caching 시작하기"^]
