---
sidebar: sidebar 
permalink: use/task-create-fsx-system.html 
keywords: Amazon FSx for NetApp ONTAP, fsx, volumes, create system, delete system, access key, secret key, region, working environment, availability zones, discover, storage capacity, iops, throughput, security group, security, bluexp, NetApp Console 
summary: NetApp Console 에서 볼륨과 추가 데이터 서비스를 추가하고 관리하기 위해 FSx for ONTAP 파일 시스템을 만들거나 검색합니다. 
---
= ONTAP 파일 시스템용 FSx를 생성하거나 검색합니다.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Console 에서 볼륨과 추가 데이터 서비스를 추가하고 관리하기 위해 FSx for ONTAP 파일 시스템을 만들거나 검색합니다.



== ONTAP 시스템용 FSx 생성

첫 번째 단계는 ONTAP 파일 시스템을 위한 FSx를 만드는 것입니다.  AWS Management Console에서 이미 FSx for ONTAP 파일 시스템을 생성한 경우 다음을 수행할 수 있습니다.link:task-create-fsx-system.html#discover-an-existing-fsx-for-ontap-file-system["NetApp Console 사용하여 검색하세요"] .

.이 작업에 관하여
파일 시스템을 생성하면 스토리지 VM이 생성됩니다.

.시작하기 전에
FSx for ONTAP 파일 시스템을 생성하기 전에 다음이 필요합니다.

* Workload Factory에 FSx for ONTAP 파일 시스템을 만드는 데 필요한 권한을 부여하는 IAM 역할의 ARN입니다. link:../requirements/task-setting-up-permissions-fsx.html["AWS 계정에 권한을 부여하는 방법을 알아보세요"^] .
* FSx for ONTAP 인스턴스를 생성할 지역 및 VPC 정보입니다.




== ONTAP 파일 시스템용 FSx 생성

_빠른 생성_ 또는 _고급 생성_을 사용하여 FSx for ONTAP 파일 시스템을 생성할 수 있습니다.  Codebox에서 제공하는 다음 도구도 사용할 수 있습니다: REST API, CloudFormation, Terraform. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["자동화를 위해 Codebox를 사용하는 방법을 알아보세요"^] .


NOTE: Codebox에서 Terraform을 사용할 때 복사하거나 다운로드한 코드는 숨겨집니다. `fsxadmin` 그리고 `vsadmin` 비밀번호.  코드를 실행하면 비밀번호를 다시 입력해야 합니다.

[role="tabbed-block"]
====
.빠른 생성
--
빠른 생성을 사용하면 권장되는 모범 사례 구성을 사용할 수 있습니다.  FSx for ONTAP 파일 시스템을 만든 후에는 대부분의 설정을 변경할 수 있습니다.

.단계
. NetApp Console 메뉴에서 *스토리지*를 선택한 다음 *관리*를 선택합니다.
. 시스템 페이지에서 *시스템 추가*를 선택합니다.
. 위치로 *Amazon Web Services*를 선택한 다음 Amazon FSx for NetApp ONTAP 대해 *새로 추가*를 선택합니다.
. FSx for ONTAP 파일 시스템 만들기 페이지에서 *빠른 만들기*를 선택합니다.
+
저장된 구성을 로드할 수도 있습니다.

. 파일 시스템 일반 구성에서 다음을 제공합니다.
+
.. *AWS 자격 증명*: AWS 자격 증명을 추가하거나 자격 증명 없이 계속 진행하세요.  자격 증명 없이도 Codebox에서 부분적으로 완성된 코드를 복사하여 다운로드할 수 있습니다.  이 코드는 누락된 정보(예: 자격 증명)를 채우거나 코드를 실행하기 전에 특정 데이터를 사용자 지정할 수 있는 템플릿처럼 사용할 수 있습니다.
.. *파일 시스템 이름*: 파일 시스템의 이름을 입력하세요.
.. *배포 토폴로지*: 배포 토폴로지를 선택하세요.
+
*** 스케일업 토폴로지는 하나의 파일 시스템을 사용하여 데이터를 분산하고 데이터 증가에 맞춰 크기를 늘릴 수 있는 방식입니다.
*** 확장형 토폴로지는 데이터 분산을 위해 두 개 이상의 파일 시스템을 사용하는 방식입니다.


.. *HA 쌍*: HA 쌍의 수를 입력하세요.
+
*** 확장 배포의 경우 HA 쌍을 하나만 가질 수 있습니다.
*** 확장형 배포의 경우 2~12개의 HA 쌍을 사용할 수 있습니다.


.. *배포 유형*: 배포 유형을 선택하세요.
+
*** 단일 가용성 영역(단일 AZ) 배포: 하드웨어 오류를 모니터링하고 오류 발생 시 인프라 구성 요소를 자동으로 교체하여 가용성을 보장합니다.  구성 요소 오류로부터 데이터를 보호하기 위해 가용성 영역 내에서 데이터를 자동으로 복제하여 높은 내구성을 달성합니다.
*** 다중 가용성 영역(Multi-AZ) 배포: 가용성 영역을 사용할 수 없는 경우에도 데이터에 대한 지속적인 가용성을 제공합니다.  다중 AZ 파일 시스템은 단일 AZ 파일 시스템의 모든 가용성 및 내구성 기능을 지원합니다.  Multi-AZ 파일 시스템은 공유 ONTAP 파일 데이터에 대한 높은 가용성이 필요하고 가용성 영역 전반에 걸쳐 내장된 복제 기능을 갖춘 스토리지가 필요한 비즈니스에 중요한 프로덕션 워크로드를 위해 설계되었습니다.


.. *태그*: 선택적으로 최대 50개의 태그를 추가할 수 있습니다.


. *네트워크 및 보안*의 *지역 및 VPC* 필드에서 파일 시스템의 지역과 VPC를 선택합니다.
. *파일 시스템 세부 정보*에서 다음을 제공합니다.
+
.. *SSD 저장 용량*: 저장 용량을 입력하고 저장 용량 단위를 선택하세요.
.. * ONTAP 자격 증명*: ONTAP 사용자 이름과 비밀번호를 입력하세요.
.. *SMB/CIFS 설정*: 선택 사항.  SMB/CIFS 프로토콜을 사용하여 볼륨에 액세스하려는 경우 파일 시스템을 생성하는 동안 스토리지 VM에 대한 Active Directory를 구성해야 합니다.  이 파일 시스템에 대해 생성된 스토리지 VM에 대한 다음 세부 정보를 제공합니다.
+
... *가입할 Active Directory 도메인*: Active Directory의 정규화된 도메인 이름(FQDN)을 입력하세요.
... *DNS IP 주소*: 최대 3개의 DNS IP 주소를 쉼표로 구분하여 입력하세요.
... *SMB 서버 NetBIOS 이름*: 스토리지 VM에 대해 생성할 Active Directory 컴퓨터 개체의 SMB 서버 NetBIOS 이름을 입력합니다.  이는 Active Directory에 있는 이 저장소 VM의 이름입니다.
... *사용자 이름*: 기존 Active Directory의 서비스 계정 사용자 이름을 입력합니다.
+
도메인 접두사나 접미사를 포함하지 마세요.  을 위한 `EXAMPLE\ADMIN` , 사용 `ADMIN` .

... *비밀번호*: 서비스 계정의 비밀번호를 입력하세요.
... *조직 단위*: 선택적으로 FSx for ONTAP 에 대한 컴퓨터 계정을 만들려는 조직 단위의 이름을 입력합니다.  OU는 파일 시스템에 가입하려는 조직 단위의 고유 경로 이름입니다.
... *위임된 관리자 그룹*: 선택적으로, 파일 시스템을 관리할 수 있는 Active Directory의 그룹 이름을 입력합니다.
+
AWS Managed Microsoft AD를 사용하는 경우 AWS 위임 FSx 관리자, AWS 위임 관리자 또는 OU에 대한 위임된 권한이 있는 사용자 지정 그룹과 같은 그룹을 지정해야 합니다.

+
자체 관리 AD에 가입하는 경우 AD의 그룹 이름을 사용하세요.  기본 그룹은 `Domain Admins` .





. *요약*을 열어 정의한 구성을 검토하세요.  필요한 경우 파일 시스템을 저장하거나 생성하기 전에 이때 설정을 변경할 수 있습니다.
. 파일 시스템을 저장하거나 생성합니다.


.결과
파일 시스템을 생성한 경우 새로운 FSx for ONTAP 구성이 시스템 페이지에 나타납니다.

NetApp Console 의 워크로드, ONTAP System Manager, AWS CloudFormation 등 다양한 방법으로 FSx for ONTAP 파일 시스템을 관리할 수 있습니다. 자세한 내용은 link:task-manage-fsx-systems.html["ONTAP 파일 시스템용 FSx 관리"] .

--
.고급 생성
--
고급 생성을 사용하면 가용성, 보안, 백업, 유지 관리를 포함한 모든 구성 옵션을 설정할 수 있습니다.

.단계
. NetApp Console 메뉴에서 *스토리지*를 선택한 다음 *관리*를 선택합니다.
. 시스템 페이지에서 *시스템 추가*를 선택합니다.
. 위치로 *Amazon Web Services*를 선택한 다음 Amazon FSx for NetApp ONTAP 대해 *새로 추가*를 선택합니다.
. ONTAP 용 FSx 만들기 페이지에서 *고급 만들기*를 선택합니다.
+
저장된 구성을 로드할 수도 있습니다.

. 파일 시스템 일반 구성에서 다음을 제공합니다.
+
.. *AWS 자격 증명*: Workload Factory에 AWS 자격 증명을 추가하거나 자격 증명 없이 계속할지 선택합니다.
.. *파일 시스템 이름*: 파일 시스템의 이름을 입력하세요.
.. *배포 토폴로지*: 배포 토폴로지를 선택하세요.
+
*** 스케일업 토폴로지는 하나의 파일 시스템을 사용하여 데이터를 분산하고 데이터 증가에 맞춰 크기를 늘릴 수 있는 방식입니다.
*** 확장형 토폴로지는 데이터 분산을 위해 두 개 이상의 파일 시스템을 사용하는 방식입니다.


.. *HA 쌍*: HA 쌍의 수를 입력하세요.
+
*** 확장 배포의 경우 HA 쌍을 하나만 가질 수 있습니다.
*** 확장형 배포의 경우 2~12개의 HA 쌍을 사용할 수 있습니다.


.. *배포 유형*: 배포 유형을 선택하세요.
+
*** 단일 가용성 영역(단일 AZ) 배포: 하드웨어 오류를 모니터링하고 오류 발생 시 인프라 구성 요소를 자동으로 교체하여 가용성을 보장합니다.  구성 요소 오류로부터 데이터를 보호하기 위해 가용성 영역 내에서 데이터를 자동으로 복제하여 높은 내구성을 달성합니다.
*** 다중 가용성 영역(Multi-AZ) 배포: 가용성 영역을 사용할 수 없는 경우에도 데이터에 대한 지속적인 가용성을 제공합니다.  다중 AZ 파일 시스템은 단일 AZ 파일 시스템의 모든 가용성 및 내구성 기능을 지원합니다.  Multi-AZ 파일 시스템은 공유 ONTAP 파일 데이터에 대한 높은 가용성이 필요하고 가용성 영역 전반에 걸쳐 내장된 복제 기능을 갖춘 스토리지가 필요한 비즈니스에 중요한 프로덕션 워크로드를 위해 설계되었습니다.


.. *태그*: 선택적으로 최대 50개의 태그를 추가할 수 있습니다.


. 네트워크 및 보안에서 다음을 제공합니다.
+
.. *지역 및 VPC*: 파일 시스템에 대한 지역과 VPC를 선택합니다.
.. *보안 그룹*: 보안 그룹을 만들거나 기존 보안 그룹을 사용합니다.
.. *가용 영역*: 가용성 영역과 서브넷을 선택하세요.
+
*** 클러스터 구성 노드 1의 경우: 가용성 영역과 서브넷을 선택합니다.
*** 클러스터 구성 노드 2의 경우: 가용성 영역과 서브넷을 선택합니다.


.. *VPC 경로 테이블*: 클라이언트가 볼륨에 액세스할 수 있도록 VPC 경로 테이블을 선택합니다.
.. *엔드포인트 IP 주소 범위*: *VPC 외부의 유동 IP 주소 범위*를 선택하거나 *IP 주소 범위 입력*을 선택하고 IP 주소 범위를 입력합니다.
.. *암호화*: 드롭다운에서 암호화 키 이름을 선택합니다.


. 파일 시스템 세부 정보에서 다음을 제공합니다.
+
.. *SSD 저장 용량*: 저장 용량을 입력하고 저장 용량 단위를 선택하세요.
.. *프로비저닝된 IOPS*: *자동* 또는 *사용자 프로비저닝*을 선택합니다.
.. *HA 쌍당 처리량 용량*: HA 쌍당 처리량 용량을 선택하세요.
.. * ONTAP 자격 증명*: ONTAP 사용자 이름과 비밀번호를 입력하세요.
.. *저장소 VM 자격 증명*: 사용자 이름을 입력하세요.  비밀번호는 이 파일 시스템에만 적용할 수 있으며, ONTAP 자격 증명에 입력한 것과 동일한 비밀번호를 사용할 수도 있습니다.
.. *SMB/CIFS 설정*: 선택 사항.  SMB/CIFS 프로토콜을 사용하여 볼륨에 액세스하려는 경우 파일 시스템을 생성하는 동안 스토리지 VM에 대한 Active Directory를 구성해야 합니다.  이 파일 시스템에 대해 생성된 스토리지 VM에 대한 다음 세부 정보를 제공합니다.
+
... *가입할 Active Directory 도메인*: Active Directory의 정규화된 도메인 이름(FQDN)을 입력하세요.
... *DNS IP 주소*: 최대 3개의 DNS IP 주소를 쉼표로 구분하여 입력하세요.
... *SMB 서버 NetBIOS 이름*: 스토리지 VM에 대해 생성할 Active Directory 컴퓨터 개체의 SMB 서버 NetBIOS 이름을 입력합니다.  이는 Active Directory에 있는 이 저장소 VM의 이름입니다.
... *사용자 이름*: 기존 Active Directory의 서비스 계정 사용자 이름을 입력합니다.
+
도메인 접두사나 접미사를 포함하지 마세요.  을 위한 `EXAMPLE\ADMIN` , 사용 `ADMIN` .

... *비밀번호*: 서비스 계정의 비밀번호를 입력하세요.
... *조직 단위*: 선택적으로 FSx for ONTAP 에 대한 컴퓨터 계정을 만들려는 조직 단위의 이름을 입력합니다.  OU는 파일 시스템에 가입하려는 조직 단위의 고유 경로 이름입니다.
... *위임된 관리자 그룹*: 선택적으로, 파일 시스템을 관리할 수 있는 Active Directory의 그룹 이름을 입력합니다.
+
AWS Managed Microsoft AD를 사용하는 경우 AWS 위임 FSx 관리자, AWS 위임 관리자 또는 OU에 대한 위임된 권한이 있는 사용자 지정 그룹과 같은 그룹을 지정해야 합니다.

+
자체 관리 AD에 가입하는 경우 AD의 그룹 이름을 사용하세요.  기본 그룹은 `Domain Admins` .





. 백업 및 유지 관리에서 다음을 제공합니다.
+
.. *FSx for ONTAP 백업*: 기본적으로 매일 자동 백업이 활성화되어 있습니다.  원하시면 비활성화하세요.
+
... *자동 백업 보존 기간*: 자동 백업을 보존할 일수를 입력하세요.
... *매일 자동 백업 창*: *기본 설정 없음*(매일 백업 시작 시간이 선택됨) 또는 *매일 백업 시작 시간 선택*을 선택하고 시작 시간을 지정합니다.
... *주간 유지 관리 기간*: *선호 사항 없음*(주간 유지 관리 기간 시작 시간이 선택됨) 또는 *30분 주간 유지 관리 기간의 시작 시간 선택*을 선택하고 시작 시간을 지정합니다.




. 파일 시스템을 저장하거나 생성합니다.


.결과
파일 시스템을 생성한 경우 새로운 FSx for ONTAP 구성이 시스템 페이지에 나타납니다.

NetApp Console 의 워크로드, ONTAP System Manager, AWS CloudFormation 등 다양한 방법으로 FSx for ONTAP 파일 시스템을 관리할 수 있습니다. 자세한 내용은 link:task-manage-fsx-systems.html["ONTAP 파일 시스템용 FSx 관리"] .

--
====


== 기존 FSx for ONTAP 파일 시스템을 검색합니다.

이전에 NetApp Console 에서 AWS 자격 증명을 제공한 경우 Discoverable systems 페이지에서 FSx for ONTAP 파일 시스템을 자동으로 검색할 수 있습니다.  또한, 사용 가능한 데이터 서비스를 검토할 수도 있습니다.

.이 작업에 관하여
FSx for ONTAP 파일 시스템은 계정 내에서 한 번만 검색하여 하나의 작업 공간에 연결할 수 있습니다.  나중에 파일 시스템을 제거하여 다른 작업 공간에 다시 연결할 수 있습니다.

.단계
. NetApp Console 메뉴에서 *스토리지*를 선택한 다음 *관리*를 선택하고 * Discoverable systems*을 선택합니다.
. 검색된 FSx for ONTAP 파일 시스템의 수가 표시됩니다. *발견*을 선택하세요.
. 하나 이상의 파일 시스템을 선택하고 *검색*을 선택하여 시스템 페이지에 추가합니다.


[NOTE]
====
* 이름이 지정되지 않은 클러스터를 선택하면 클러스터 이름을 입력하라는 메시지가 표시됩니다.
* 콘솔에서 FSx for ONTAP 파일 시스템을 관리하는 데 필요한 자격 증명이 없는 클러스터를 선택하면 필요한 권한이 있는 자격 증명을 선택하라는 메시지가 표시됩니다.


====
.결과
콘솔은 시스템 페이지에서 발견된 FSx for ONTAP 파일 시스템을 표시합니다.  NetApp Console 의 워크로드, ONTAP System Manager, AWS CloudFormation 등 다양한 방법으로 FSx for ONTAP 파일 시스템을 관리할 수 있습니다. 자세한 내용은 link:task-manage-fsx-systems.html["ONTAP 파일 시스템용 FSx 관리"] .
